<?php


namespace AppBundle\Setting;


class InbreedingCoefficientSetting
{
    const DEFAULT_GENERATION_OF_ASCENDANTS = 7;
    const DECIMAL_PRECISION = 5;

    const DISPLAY_DECIMAL_PRECISION = 1;

    const LOG_LOOP_DETAILS = false;

    const LOOP_MAX_DURATION_IN_HOURS = 3;

    /**
     * MUST BE AT LEAST 1 SECOND!
     */
    const QUEUE_EMPTY_TIMEOUT_SECONDS_ADMIN = 10;
    const QUEUE_EMPTY_TIMEOUT_SECONDS_REPORT = 3;
    const QUEUE_EMPTY_TIMEOUT_SECONDS_PARENT_PAIRS = 3;
    const QUEUE_LOCKED_TIMEOUT_SECONDS_ADMIN = 2;
    const QUEUE_LOCKED_TIMEOUT_SECONDS_REPORT = 3;
    const QUEUE_LOCKED_TIMEOUT_SECONDS_PARENT_PAIRS = 2;
}
