
imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # Disable SQL logging, this fixes the PHP memory leaks on the production server
        logging: false

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        # enable metadata caching
        metadata_cache_driver: redis
        # enable query caching
        query_cache_driver: redis
        # enable resultset caching
        result_cache_driver: redis
services:
    twig.extension.stringloader:
        class: Twig_Extension_StringLoader
        tags:
        - { name: twig.extension }

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    encryption: "%mailer_encryption%"
    port:      "%mailer_port%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Redis Configuration
snc_redis:
    # configure predis as client
    clients:
        sncredis:
             type: predis
             alias: sncredis
             dsn:
                  - "%redis_host%"
             options:
                  replication: false
                  connection_timeout: 10
                  read_write_timeout: 30
    # configure predis session
    session:
        client: sncredis
        prefix: "nsfo:api"
        ttl: 31536000
    # configure doctrine caching
    doctrine:
        metadata_cache:
            client: sncredis
            entity_manager: [default, cached]
        result_cache:
            client: sncredis
            entity_manager: [default, cached]
        query_cache:
            client: sncredis
            entity_manager: [default, cached]

# Nelmio CORS bundle
nelmio_cors:
   defaults:
       allow_credentials: false
       allow_origin: []
       allow_headers: []
       allow_methods: []
       expose_headers: []
       max_age: 0
       hosts: []
       origin_regex: false
   paths:
       '^/api/':
           allow_origin: ['*']
           allow_headers: ['*']
           allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
           max_age: 3600
       '^/':
           origin_regex: true
           allow_origin: ['*']
           allow_headers: ['*']
           allow_methods: ['POST', 'PUT', 'GET', 'DELETE', 'OPTIONS']
           max_age: 3600
           hosts: ['^api\.']

nelmio_api_doc: ~

monolog:
    handlers:
        console:
            type: console
            verbosity_levels:
                VERBOSITY_NORMAL: NOTICE
