# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.entity.validate:
        class: AppBundle\Service\ValidateEntityService
        arguments: ['@validator', '@jms_serializer']

    app.aws.queueservice:
        class: AppBundle\Service\AWSQueueService
        arguments:
          credentials: ['%aws_access_key_id%', '%aws_secret_key%']
          region: %aws_sqs_region%
          version: %aws_sqs_version%
          queueIds: ['%aws_sqs_queue_prod%', '%aws_sqs_queue_stage%', '%aws_sqs_queue_dev%', '%aws_sqs_queue_test%', '%aws_sqs_queue_local%']
          currentEnv: %kernel.environment%

    app.aws.storageservice:
        class: AppBundle\Service\AWSSimpleStorageService
        arguments:
          credentials: ['%aws_access_key_id%', '%aws_secret_key%']
          region: %aws_s3_region%
          version: %aws_s3_version%
          bucket: %aws_s3_bucket%
          currentEnv: %kernel.environment%

    app.doctrine.entitygetter:
        class: AppBundle\Service\EntityGetter
        arguments: ['@doctrine.orm.entity_manager']

    app.modifier.message:
        class: AppBundle\Component\Modifier\MessageModifier
        arguments: ['@doctrine.orm.entity_manager']

    app.modifier.animalremover:
        class: AppBundle\Component\Modifier\AnimalRemover
        arguments: ['@doctrine.orm.entity_manager']

    app.animallocation.history:
        class: AppBundle\Service\AnimalLocationHistoryService
        arguments: ['@doctrine.orm.entity_manager']

    app.messagebuilder.base:
        class: AppBundle\Component\MessageBuilderBase
        arguments:
          entityManager: ['@doctrine.orm.entity_manager']
          currentEnv: %kernel.environment%

    app.routine.mixblup:
        class: AppBundle\Service\MixBlupService
        arguments:
          entityManager: ['@doctrine.orm.entity_manager']
          AWSSimpleStorageService: '@app.aws.storageservice'
          AWSQueueService: '@app.aws.queueservice'
          currentEnv: %kernel.environment%
          rootDir: %kernel.cache_dir%

    app.serializer.ir:
        class: AppBundle\Service\IRSerializer
        arguments: ['@jms_serializer', '@doctrine.orm.entity_manager', '@app.doctrine.entitygetter']

    app.health.updater:
        class: AppBundle\Service\HealthService
        arguments: ['@doctrine.orm.entity_manager']

    app.authenticator.token:
        class: AppBundle\Component\Authentication\TokenAuthenticator
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          httpUtil: '@security.http_utils'
          unauthedPaths: ['/api/v1/doc', '/api/v1/auth/register', '/api/v1/auth/authorize']
        public: false