# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.entity.validate:
        class: AppBundle\Service\ValidateEntityService
        arguments: ['@validator', '@jms_serializer']


    app.cli.options:
        class: AppBundle\Service\CliOptionsService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '%kernel.root_dir%'
          - '@app.initializer.birth_progress'
          - '@app.datafix.animals.duplicate'
          - '@app.cli.gender_changer'
          - '@app.info.parameters'
          - '@app.migrator.inspector'
          - '@app.cli.internal_worker.depart'
          - '@app.cli.mixblup'
          - '@app.initializer.stored_procedure'
          - '@app.datafix.ubn'
          - '@app.migrator.vsm'

    app.cli.gender_changer:
        class: AppBundle\Service\DataFix\GenderChangeCommandService
        arguments:
          - '@doctrine.orm.entity_manager'

    app.cli.internal_worker.depart:
        class: AppBundle\Service\Worker\DepartInternalWorkerCliOptions
        arguments:
          - '@doctrine.orm.entity_manager'

    app.cli.mixblup:
        class: AppBundle\Service\MixBlupCliOptionsService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '@app.report.breed_values_overview'
          - '@app.breed.valueprinter'
          - '@app.breed.value'
          - '@app.breed.index'
          - '@app.excel.service'
          - '@app.migrator.lamb_meat_index'
          - '@app.mixblup.input'
          - '@app.mixblup.input.validate'
          - '@app.mixblup.output'
          - '@app.report.pedigree_register'

    app.info.parameters:
        class: AppBundle\Service\InfoService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '@app.aws.storageservice'
          - '%kernel.environment%'
          - '%environment%'
          - '%kernel.root_dir%'
          - '%kernel.cache_dir%'
          - '%redis_host%'
          - '@app.aws.queueservice.external'
          - '@app.aws.queueservice.internal'
          - '@app.aws.queueservice.mixblup_input'
          - '@app.aws.queueservice.mixblup_output'


    app.request.message_builder:
        class: AppBundle\Component\RequestMessageBuilder
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@app.serializer.ir'
          - '%kernel.environment%'


    app.aws.queueservice.workers_base:
        abstract: true
        arguments:
        #NOTE! Don't use named keys here! That will prevent the child services from properly overriding the arguments.
          - placeholder_to_override #queueIdPrefix
          - ['%aws_access_key_id%', '%aws_secret_key%'] #credentials
          - %aws_sqs_region% #region
          - %aws_sqs_version% #version
          - %environment% #currentEnv

    app.aws.queueservice.external:
        class: AppBundle\Service\AwsExternalQueueService
        parent: app.aws.queueservice.workers_base
        arguments: { index_0: '%aws_sqs_queue_exteral_prefix%' }

    app.aws.queueservice.internal:
        class: AppBundle\Service\AwsInternalQueueService
        parent: app.aws.queueservice.workers_base
        arguments: { index_0: '%aws_sqs_queue_interal_prefix%' }

    app.aws.queueservice.mixblup_input:
        class: AppBundle\Service\MixBlupInputQueueService
        parent: app.aws.queueservice.workers_base
        arguments: { index_0: '%aws_sqs_queue_mixblup_input_prefix%' }

    app.aws.queueservice.mixblup_output:
        class: AppBundle\Service\MixBlupOutputQueueService
        parent: app.aws.queueservice.workers_base
        arguments: { index_0: '%aws_sqs_queue_mixblup_output_prefix%' }

    app.aws.storageservice:
        class: AppBundle\Service\AWSSimpleStorageService
        arguments:
          credentials: ['%aws_access_key_id%', '%aws_secret_key%']
          region: %aws_s3_region%
          version: %aws_s3_version%
          bucket: %aws_s3_bucket%
          currentEnv: %environment%

    app.doctrine.entitygetter:
        class: AppBundle\Service\EntityGetter
        arguments: ['@doctrine.orm.entity_manager']

    app.modifier.message:
        class: AppBundle\Component\Modifier\MessageModifier
        arguments: ['@doctrine.orm.entity_manager']

    app.modifier.animalremover:
        class: AppBundle\Component\Modifier\AnimalRemover
        arguments: ['@doctrine.orm.entity_manager']

    app.animallocation.history:
        class: AppBundle\Service\AnimalLocationHistoryService
        arguments: ['@doctrine.orm.entity_manager']

    app.messagebuilder.base:
        class: AppBundle\Component\MessageBuilderBase
        arguments:
          entityManager: ['@doctrine.orm.entity_manager']
          currentEnv: %environment%

    app.mixblup.input:
        class: AppBundle\Service\MixBlupInputFilesService
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          AWSSimpleStorageService: '@app.aws.storageservice'
          MixBlupInputQueueService: '@app.aws.queueservice.mixblup_input'
          currentEnv: %environment%
          cacheDir: %kernel.cache_dir%
          logger: '@logger'

    app.mixblup.output:
        class: AppBundle\Service\MixBlupOutputFilesService
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          AWSSimpleStorageService: '@app.aws.storageservice'
          MixBlupOutputQueueService: '@app.aws.queueservice.mixblup_output'
          currentEnv: %environment%
          cacheDir: %kernel.cache_dir%
          logger: '@logger'

    app.mixblup.input.validate:
        class: AppBundle\Component\MixBlup\MixBlupInputFileValidator
        arguments: ['%kernel.cache_dir%']



    app.datafix.base.duplicate:
        abstract: true
        arguments:
        #NOTE! Don't use named keys here! That will prevent the child services from properly overriding the arguments.
          - '@doctrine.orm.entity_manager'

    app.datafix.animals.duplicate:
        parent: app.datafix.base.duplicate
        class: AppBundle\Service\DataFix\DuplicateAnimalsFixer

    app.datafix.litter.duplicate:
        parent: app.datafix.base.duplicate
        class: AppBundle\Service\DataFix\DuplicateLitterFixer

    app.datafix.animals.exterminator:
        parent: app.datafix.base.duplicate
        class: AppBundle\Service\DataFix\AnimalExterminator

    app.datafix.ubn:
        parent: app.datafix.base.duplicate
        class: AppBundle\Service\DataFix\UbnFixer


    app.migrator.vsm:
        class: AppBundle\Service\Migration\VsmMigratorService
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          rootDir: %kernel.root_dir%
          animalTableImporter: '@app.migrator.importer.animaltable'
          animalTableMigrator: '@app.migrator.animaltable'
          birthMigrator: '@app.migrator.birth'
          dateOfDeathMigrator: '@app.migrator.date_of_death'
          exteriorMigrator: '@app.migrator.exteriors'
          litterMigrator: '@app.migrator.litters'
          tagReplaceMigrator: '@app.migrator.tagreplace'
          wormResistanceMigrator: '@app.migrator.wormresistance'
          duplicateAnimalsFixer: '@app.datafix.animals.duplicate'
          duplicateLitterFixer: '@app.datafix.litter.duplicate'

    app.migrator.base:
        abstract: true
        arguments:
        #NOTE! Don't use named keys here! That will prevent the child services from properly overriding the arguments.
          - '@doctrine.orm.entity_manager'
          - %kernel.root_dir%

    app.migrator.importer.animaltable:
        class: AppBundle\Service\Migration\AnimalTableImporter
        arguments:
          - '@doctrine.orm.entity_manager'
          - %kernel.root_dir%
          - '@app.datafix.animals.duplicate'
          - '@app.datafix.ubn'

    app.migrator.animaltable:
        class: AppBundle\Service\Migration\AnimalTableMigrator
        arguments:
          - '@doctrine.orm.entity_manager'
          - %kernel.root_dir%
          - '@app.datafix.ubn'

    app.migrator.birth:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\BirthDataMigrator

    app.initializer.birth_progress:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\BirthProgressInitializer

    app.initializer.stored_procedure:
        class: AppBundle\Service\Migration\StoredProcedureInitializer
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'

    app.migrator.client:
        class: AppBundle\Service\Migration\ClientMigrator
        arguments:
          - '@doctrine.orm.entity_manager'
          - %kernel.root_dir%
          - '@security.password_encoder'

    app.migrator.date_of_death:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\DateOfDeathMigrator

    app.migrator.exteriors:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\ExteriorMigrator

    app.migrator.inspector:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\InspectorMigrator

    app.migrator.lamb_meat_index:
        class: AppBundle\Service\Migration\LambMeatIndexMigrator
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'

    app.migrator.litters:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\LitterMigrator

    app.migrator.tagreplace:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\TagReplaceMigrator

    app.migrator.wormresistance:
        parent: app.migrator.base
        class: AppBundle\Service\Migration\WormResistanceMigrator

    app.breed.index:
        class: AppBundle\Service\BreedIndexService
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          logger: '@logger'

    app.breed.value:
        class: AppBundle\Service\BreedValueService
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          logger: '@logger'

    app.breed.valueprinter:
        class: AppBundle\Service\BreedValuePrinter
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          logger: '@logger'
          cacheDir: %kernel.cache_dir%

    app.excel.service:
        class: AppBundle\Service\ExcelService
        arguments:
          excelBundle: '@phpexcel'
          cacheDir: %kernel.cache_dir%
          logger: '@logger'

    app.serializer.ir:
        class: AppBundle\Service\IRSerializer
        arguments: ['@jms_serializer', '@doctrine.orm.entity_manager', '@app.doctrine.entitygetter']

    app.health.updater:
        class: AppBundle\Service\HealthService
        arguments: ['@doctrine.orm.entity_manager']

    app.authenticator.token:
        class: AppBundle\Component\Authentication\TokenAuthenticator
        arguments:
          entityManager: '@doctrine.orm.entity_manager'
          httpUtil: '@security.http_utils'
          unauthedPaths: ['/api/v1/doc', '/api/v1/auth/register', '/api/v1/auth/authorize']
        public: false

    app.cache:
        class: AppBundle\Service\CacheService
        arguments:
          - '@snc_redis.sncredis'

    app.user:
        class: AppBundle\Service\UserService
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@security.token_storage'

    app.report.base:
        abstract: true
        arguments:
        #NOTE! Don't use named keys here! That will prevent the child services from properly overriding the arguments.
          - '@doctrine.orm.entity_manager'
          - '@app.excel.service'
          - '@logger'
          - '@app.aws.storageservice'
          - '@app.writer.csv_from_sql_results'
          - '@app.user'
          - '@templating'
          - '@knp_snappy.pdf'
          - '%kernel.cache_dir%'
          - '%kernel.root_dir%'

    app.report.livestock:
        parent: app.report.base
        class: AppBundle\Service\Report\LiveStockReportService

    app.report.pedigree_certificates:
        parent: app.report.base
        class: AppBundle\Service\Report\PedigreeCertificateReportService

    app.report.pedigree_register:
        parent: app.report.base
        class: AppBundle\Service\Report\PedigreeRegisterOverviewReportService

    app.report.breed_values_overview:
        parent: app.report.base
        class: AppBundle\Service\Report\BreedValuesOverviewReportService

    app.report.inbreeding_coefficient:
        parent: app.report.base
        class: AppBundle\Service\Report\InbreedingCoefficientReportService

    app.writer.csv_from_sql_results:
        class: AppBundle\Service\CsvFromSqlResultsWriterService
        arguments:
            - '@doctrine.orm.entity_manager'
            - '%kernel.cache_dir%'

    app.email:
        class: AppBundle\Service\EmailService
        arguments:
          - '@mailer'
          - '%mailer_source_address%'
          - '@templating'
          - '%kernel.environment%'

    app.abstract_base.controller:
        abstract: true
        arguments:
          - '@app.cache'
          - '@doctrine.orm.entity_manager'
          - '@app.user'

    app.abstract_base.auth:
        abstract: true
        arguments:
          - '@app.cache'
          - '@app.email'
          - '@doctrine.orm.entity_manager'
          - '@app.user'
          - '@security.password_encoder'

    app.security.auth:
        parent: app.abstract_base.auth
        class: AppBundle\Service\AuthService

    app.security.admin_auth:
        parent: app.abstract_base.auth
        class: AppBundle\Service\AdminAuthService

    app.admin:
        parent: app.abstract_base.auth
        class: AppBundle\Service\AdminService

    app.admin.profile:
        parent: app.abstract_base.auth
        class: AppBundle\Service\AdminProfileService

    app.abstract_base.declare:
        abstract: true
        arguments:
          - '@app.aws.queueservice.external'
          - '@app.cache'
          - '@doctrine.orm.entity_manager'
          - '@app.serializer.ir'
          - '@app.request.message_builder'
          - '@app.user'

    app.animal:
        parent: app.abstract_base.declare
        class: AppBundle\Service\AnimalService

    app.arrival:
        class: AppBundle\Service\ArrivalService
        arguments:
          - '@app.aws.queueservice.external'
          - '@app.cache'
          - '@doctrine.orm.entity_manager'
          - '@app.serializer.ir'
          - '@app.request.message_builder'
          - '@app.user'
          - '@app.health.updater'
          - '@app.animallocation.history'
          - '%kernel.environment%'

    app.birth:
        class: AppBundle\Service\BirthService
        arguments:
          - '@app.aws.queueservice.external'
          - '@app.cache'
          - '@doctrine.orm.entity_manager'
          - '@app.serializer.ir'
          - '@app.request.message_builder'
          - '@app.user'
          - '@logger'
          - '@app.aws.queueservice.internal'
          - '@app.doctrine.entitygetter'

    app.client:
        parent: app.abstract_base.controller
        class: AppBundle\Service\ClientService

    app.collar:
        parent: app.abstract_base.controller
        class: AppBundle\Service\CollarService

    app.company:
        parent: app.abstract_base.auth
        class: AppBundle\Service\CompanyService

    app.component:
        parent: app.abstract_base.controller
        class: AppBundle\Service\ComponentService

    app.contact:
        parent: app.abstract_base.auth
        class: AppBundle\Service\ContactService

    app.content_management:
        parent: app.abstract_base.controller
        class: AppBundle\Service\ContentManagementService

    app.country:
        parent: app.abstract_base.declare
        class: AppBundle\Service\CountryService

    app.dashboard:
        parent: app.abstract_base.controller
        class: AppBundle\Service\DashboardService


    app.depart:
        class: AppBundle\Service\DepartService
        arguments:
          - '@app.aws.queueservice.external'
          - '@app.cache'
          - '@doctrine.orm.entity_manager'
          - '@app.serializer.ir'
          - '@app.request.message_builder'
          - '@app.user'
          - '%kernel.environment%'

    app.export:
        parent: app.abstract_base.declare
        class: AppBundle\Service\ExportService

    app.import:
        parent: app.abstract_base.declare
        class: AppBundle\Service\ImportService

    app.loss:
        parent: app.abstract_base.declare
        class: AppBundle\Service\LossService
