# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    api.entity.validate:
        class: AppBundle\Service\ValidateEntityService
        arguments: ['@validator', '@jms_serializer']


    app.aws.queueservice:
        class: AppBundle\Service\AWSQueueService
        arguments:
          credentials: ['%aws_access_key_id%', '%aws_secret_key%']
          region: %aws_sqs_region%
          version: %aws_sqs_version%
          queueIds: ['%aws_sqs_queue_prod%', '%aws_sqs_queue_dev%', '%aws_sqs_queue_test%']
          currentEnv: %kernel.environment%


    app.doctrine.entitygetter:
        class: AppBundle\Service\EntityGetter
        arguments: ['@doctrine.orm.entity_manager']


    app.messagebuilder.base:
        class: AppBundle\Component\MessageBuilderBase
        arguments: ['@doctrine.orm.entity_manager']


    app.serializer.decrappifier:
        class: AppBundle\Service\Decrappifier
        arguments: ['@jms_serializer', '@doctrine.orm.entity_manager']