<?php


namespace AppBundle\Enumerator;

/**
 * Class CommandTitle
 */
class CommandTitle
{
    const DATA_MIGRATION = 'DATA MIGRATION';
    const INSPECTOR = 'INSPECTOR';
    const PEDIGREE_REGISTER_REGISTRATION = 'PEDIGREE REGISTER REGISTRATION';
    const LEDGER_CATEGORY = 'LEDGER CATEGORY';

    const DATA_MIGRATE_2017_AND_WORM = 'MIGRATE VSM DATA 2017 JUNE & WORM RESISTANCE';
    const SCAN_MEASUREMENTS_DATA = 'SCAN MEASUREMENTS DATA';
    const MIXBLUP = 'MiXBLUP';
    const MIXBLUP_ANALYSIS_TYPE = 'MiXBLUP ANALYSIS TYPE';

    const DEPART_INTERNAL_WORKER = 'DEPART INTERNAL WORKER LOGIC USING TXT FILE OF JSON MESSAGES';
}