<?php


namespace AppBundle\Enumerator;


class JmsGroup
{
    const ACTION_LOG_ADMIN = 'ACTION_LOG_ADMIN';
    const ACTION_LOG_USER = 'ACTION_LOG_USER';
    const CONTACT_INFO = 'CONTACT_INFO';
    const DECLARE_ = 'DECLARE';
    const USER_MEASUREMENT = 'USER_MEASUREMENT';
    const TREATMENT_TEMPLATE = 'TREATMENT_TEMPLATE';
    const TREATMENT_TEMPLATE_MIN = 'TREATMENT_TEMPLATE_MIN';
}