<?php


namespace AppBundle\Enumerator;


class JmsGroup
{
    const ACTION_LOG_ADMIN = 'ACTION_LOG_ADMIN';
    const ACTION_LOG_USER = 'ACTION_LOG_USER';
    const ADMIN_HIDDEN_STATUS = 'ADMIN_HIDDEN_STATUS';

    const BASIC = 'BASIC';

    const CONTACT_INFO = 'CONTACT_INFO';

    const DECLARE_ = 'DECLARE';
    const DETAILS = 'DETAILS';

    const ERROR_DETAILS = 'ERROR_DETAILS';

    const HIDDEN_STATUS = 'HIDDEN_STATUS';

    const INVOICE = 'INVOICE';
    const INVOICE_RULE = 'INVOICE_RULE';
    const INVOICE_RULE_TEMPLATE = 'INVOICE_RULE_TEMPLATE';
    const INVOICE_SENDER_DETAILS = 'INVOICE_SENDER_DETAILS';

    const LIVESTOCK = 'LIVESTOCK';

    const MINIMAL = 'MINIMAL';

    const TREATMENT_TEMPLATE = 'TREATMENT_TEMPLATE';
    const TREATMENT_TEMPLATE_MIN = 'TREATMENT_TEMPLATE_MIN';

    const USER_MEASUREMENT = 'USER_MEASUREMENT';

    const VWA = 'VWA';
}