<?php


namespace AppBundle\Enumerator;


class JmsGroup
{
    const ACTION_LOG_ADMIN = 'ACTION_LOG_ADMIN';
    const ACTION_LOG_USER = 'ACTION_LOG_USER';
    const CONTACT_INFO = 'CONTACT_INFO';
    const DECLARE_ = 'DECLARE';

    const INVOICE = 'INVOICE';
    const INVOICE_RULE = 'INVOICE_RULE';
    const INVOICE_RULE_TEMPLATE = 'INVOICE_RULE_TEMPLATE';
    const INVOICE_SENDER_DETAILS = 'INVOICE_SENDER_DETAILS';

    const USER_MEASUREMENT = 'USER_MEASUREMENT';
    const TREATMENT_TEMPLATE = 'TREATMENT_TEMPLATE';
    const TREATMENT_TEMPLATE_MIN = 'TREATMENT_TEMPLATE_MIN';
}