<?php

namespace AppBundle\Enumerator;


class RequestType
{
    const DECLARATION_DETAIL = 'DECLARATION_DETAIL';
    const DECLARE_ARRIVAL = 'DECLARE_ARRIVAL';
    const DECLARE_BIRTH = 'DECLARE_BIRTH';
    const DECLARE_ANIMAL_FLAG = 'DECLARE_ANIMAL_FLAG';
    const DECLARE_DEPART = 'DECLARE_DEPART';
    const DECLARE_EARTAGS_TRANSFER = 'DECLARE_EARTAGS_TRANSFER';
    const DECLARE_LOSS = 'DECLARE_LOSS';
    const DECLARE_EXPORT = 'DECLARE_EXPORT';
    const DECLARE_IMPORT = 'DECLARE_IMPORT';
    const RETRIEVE_EARTAGS = 'RETRIEVE_EARTAGS';
    const REVOKE_DECLARATION = 'REVOKE_DECLARATION';
}