<?php

namespace AppBundle\Entity;
use Doctrine\ORM\Query\Expr\Base;

/**
 * TagTransferItemRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagTransferItemRequestRepository extends BaseRepository
{
}
