<?php

namespace AppBundle\Constant;


class BreedTraitCoefficient
{
    const LAMB_MEAT_INDEX_GROWTH = 220;
    const LAMB_MEAT_INDEX_MUSCLE_THICKNESS = 3.70;
    const LAMB_MEAT_INDEX_FAT = -6.34;

    const LAMB_MEAT_INDEX_GROWTH_GENETIC_VARIANCE = 0.0004839;
    const LAMB_MEAT_INDEX_MUSCLE_THICKNESS_GENETIC_VARIANCE = 1.848;
    const LAMB_MEAT_INDEX_FAT_GENETIC_VARIANCE = 0.157;

//    const LAMB_MEAT_INDEX_GROWTH_ACCURACY = 23.4;
//    const LAMB_MEAT_INDEX_MUSCLE_THICKNESS_ACCURACY = 25.3;
//    const LAMB_MEAT_INDEX_FAT_ACCURACY = 6.31;
}