<?php


namespace AppBundle\Constant;


class BreedValueLabel
{
    const FAT = 'FAT';
    const GROWTH = 'GROWTH';
    const MUSCLE_THICKNESS = 'MUSCLE_THICKNESS';
    const FAT_ACCURACY = 'FAT_ACCURACY';
    const MUSCLE_THICKNESS_ACCURACY = 'MUSCLE_THICKNESS_ACCURACY';
    const GROWTH_ACCURACY = 'GROWTH_ACCURACY';
    const FAT_RELIABILITY = 'FAT_RELIABILITY';
    const MUSCLE_THICKNESS_RELIABILITY = 'MUSCLE_THICKNESS_RELIABILITY';
    const GROWTH_RELIABILITY = 'GROWTH_RELIABILITY';
    const LAMB_MEAT_INDEX = 'LAMB_MEAT_INDEX';
    const LAMB_MEAT_INDEX_ACCURACY = 'LAMB_MEAT_INDEX_ACCURACY';
}